stages:
- test
- report
- pages
- noty

variables:
  RUN_ENVIRONMENT: dev
  RUN_TESTCASE_DIR: testcase

default:
  tags:
    - matebook # 替换为你的 GitLab Runner 支持的 tags

cache:
  key: $CI_PROJECT_ID
  paths:
    - pip-cache


before_script:
   - pwd

after_script:
   - pwd


# `test` stage
#========================================================
api-test:
  stage: test
  image: python:3.8
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    paths:
      - allure-results
    when: always
    expire_in: 7 day
  allow_failure: true
  script:
    - |
      mkdir -p pip-cache
      export PIP_CACHE_DIR="pip-cache"
      export LANG=en_US:zh_CN.UTF-8
      source /etc/profile
    - python3 -m pip install --upgrade pip
    - pip install poetry > temp.log 2>&1
    - python3 -m poetry config cache-dir /cache/pypoetry --local
    - python3 -m poetry config virtualenvs.path /cache/pypoetry/virtualenvs --local
    - python3 -m poetry install
    - mkdir -p outputs
    - python3 -m poetry run pytest ${RUN_TESTCASE_DIR} --env ${RUN_ENVIRONMENT} -s -v --alluredir=allure-results --clean-alluredir


# `report` stage
#========================================================
allure-report:
  stage: report
  image: frankescobar/allure-docker-service:latest # ref: https://github.com/fescobar/allure-docker-service
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    paths:
      - allure-report
    when: always
    expire_in: 7 day
  script: # 这个镜像只能使用指定目录 allure-results & allure-report，其他目录无写入权限。
    - |
      if [[ -d "allure-results" ]]; then
        allure generate -c allure-results -o allure-report --clean
      fi



# `noty` stage
#========================================================
pages: # For GitLab Pages, this job has a specific name, called pages.
  stage: pages
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    paths:
      - allure-report
      - public # GitLab Pages only considers files in a directory called public.
    when: always
    expire_in: 7 day
  script:
    - mkdir public
    - cp -r allure-report/* public
    - echo $CI_PAGES_URL
    - echo https://${CI_PROJECT_NAMESPACE}.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/allure-report/index.html


# `noty` stage
#========================================================
noty-dingtalk:
  stage: noty
  script:
    - pwd # TODO

noty-feishu:
  stage: noty
  script:
    - pwd # TODO